### PR TITLE
Map layout

### PR DESCRIPTION
**Pull request by ceelman**
#10 
This script contains an algorithm simulating generating rooms in a random pattern such that there is still a path from the starting room to the exit room. Currently only simulates the level generation, must be integrated with the actual room objects in order to function for the purposes of the game.

### CODE REVIEW

**Comment by yichenwa** [comment]
Thank you for working late into night

**Comment by jessehartloff** [comment]
Did anyone review this pull request?

**Comment by ceelman** [comment]
We adjusted the settings for the master branch and develop branch to be protected and require a reviewer, so I believe someone had to perform a review on this pull request. This pull request contains scripts I created for dealing with map generation, and it looks like Yichen performed the code review on the pull request. Does that answer your question?

**Comment by ceelman** [comment]
Oh, I see now that under the reviewer settings it says this pull request is still waiting on a review from Yichen. And yet she performed the actual merge. Is it possible to approve the merge as a reviewer without formally "approving" the review?

**Pull request merged**
